version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ter-hyperplanning-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "BackendConnect2026"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./script:/script
    networks:
      - ter_hyperplanning_network

  adminer:
    image: adminer
    container_name: ter-hyperplanning-adminer
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
      ADMINER_DEFAULT_DB: ter_hyperplanning
    ports:
      - "8080:8080"
    networks:
      - ter_hyperplanning_network

volumes:
  sqlserver_data:

networks:
  ter_hyperplanning_network:
    driver: bridge
