// <auto-generated />
using System;
using HP2.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HP2.Infrastructure.Migrations
{
    [DbContext(typeof(TerHyperplanningContext))]
    partial class TerHyperplanningContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Attend", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_id");

                    b.HasKey("GroupId", "SessionId")
                        .HasName("PK__Attend__03EC865D5035A816");

                    b.HasIndex("SessionId");

                    b.ToTable("Attend", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Admin", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.HasKey("UserId")
                        .HasName("PK__Admin__B9BE370F05D6D465");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c22107c-0651-f328-9d16-c4eb18aed5c3"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Assign", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("track_id");

                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id");

                    b.Property<int>("HourlyVolume")
                        .HasColumnType("int")
                        .HasColumnName("hourly_volume");

                    b.HasKey("TrackId", "CourseId")
                        .HasName("PK__Assign__DC1D2754232CB863");

                    b.HasIndex("CourseId");

                    b.ToTable("Assign", (string)null);

                    b.HasData(
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "2d4557a7-a48d-9926-3e2b-bc820396b11a",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "2f451339-dd0d-df32-93e6-c6e1eeb5e5ba",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "93b97065-831b-a4dc-8179-be986f0772b8",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "24027d5d-e151-9a00-fd19-ac11d27b8189",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "3b835d91-4f08-07ef-d4d5-575947097601",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "02e0e667-183a-1225-d0ed-19fe4c25f963",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "f4bf5287-38ea-e0ad-d6de-8c9aa20888a0",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "e7d426e1-99eb-6a9f-b9b5-99d9b853e3f5",
                            HourlyVolume = 20
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "03241339-1186-a90f-33bd-a9850f603619",
                            HourlyVolume = 18
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "f8c83971-d090-c665-8911-cd645e1a3c87",
                            HourlyVolume = 0
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "49ba4385-063d-7b8d-5f3f-aa1c7f573747",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "014c457e-a48a-d25e-7781-d5e483cb3dd9",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "dd9ec16b-bbf2-e937-3ef4-059bf6b9091d",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "731ac32d-6ea9-f15e-7ca2-34f99e840bd3",
                            HourlyVolume = 18
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "d059db13-ac91-760c-5bf7-6c442946e7bf",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            CourseId = "3448ddd0-694c-35d0-f117-7d5834e6ca81",
                            HourlyVolume = 18
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "2d4557a7-a48d-9926-3e2b-bc820396b11a",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "2f451339-dd0d-df32-93e6-c6e1eeb5e5ba",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "93b97065-831b-a4dc-8179-be986f0772b8",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "24027d5d-e151-9a00-fd19-ac11d27b8189",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "3b835d91-4f08-07ef-d4d5-575947097601",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "02e0e667-183a-1225-d0ed-19fe4c25f963",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "f4bf5287-38ea-e0ad-d6de-8c9aa20888a0",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "e7d426e1-99eb-6a9f-b9b5-99d9b853e3f5",
                            HourlyVolume = 12
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "03241339-1186-a90f-33bd-a9850f603619",
                            HourlyVolume = 18
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "1cb2dee1-fb12-6e48-69ea-2be4c527cbf0",
                            HourlyVolume = 0
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "49ba4385-063d-7b8d-5f3f-aa1c7f573747",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "014c457e-a48a-d25e-7781-d5e483cb3dd9",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "dd9ec16b-bbf2-e937-3ef4-059bf6b9091d",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "731ac32d-6ea9-f15e-7ca2-34f99e840bd3",
                            HourlyVolume = 18
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "d059db13-ac91-760c-5bf7-6c442946e7bf",
                            HourlyVolume = 36
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            CourseId = "3448ddd0-694c-35d0-f117-7d5834e6ca81",
                            HourlyVolume = 18
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Availability", b =>
                {
                    b.Property<string>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("availability_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_id");

                    b.Property<string>("WeekdayId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("weekday_id");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__Availabi__86E3A8015B49D583");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WeekdayId");

                    b.ToTable("Availability", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Building", b =>
                {
                    b.Property<string>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("building_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("BuildingId")
                        .HasName("PK__Building__9C9FBF7FE50B0CAC");

                    b.HasIndex(new[] { "Name" }, "UQ__Building__72E12F1B5E0C81DB")
                        .IsUnique();

                    b.ToTable("Building", (string)null);

                    b.HasData(
                        new
                        {
                            BuildingId = "2e79e28c-e7d5-27ea-f06e-6c6bb037b3d1",
                            Name = "Bâtiment A"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.ChangeStatus", b =>
                {
                    b.Property<string>("ChangeStatusId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("change_status_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.HasKey("ChangeStatusId")
                        .HasName("PK__ChangeSt__A56D1762FE15A3C1");

                    b.HasIndex(new[] { "Label" }, "UQ__ChangeSt__4823FDB21188E1FE")
                        .IsUnique();

                    b.ToTable("ChangeStatus", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__8F1EF7AEBDCFF738");

                    b.HasIndex(new[] { "Code" }, "UQ__Course__357D4CF979D2E3A3")
                        .IsUnique();

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = "2d4557a7-a48d-9926-3e2b-bc820396b11a",
                            Code = "INFO_SAD",
                            Name = "Systèmes et Applications Distribués"
                        },
                        new
                        {
                            CourseId = "2f451339-dd0d-df32-93e6-c6e1eeb5e5ba",
                            Code = "INFO_COO",
                            Name = "Conception Orientée Objet de Logiciel"
                        },
                        new
                        {
                            CourseId = "93b97065-831b-a4dc-8179-be986f0772b8",
                            Code = "INFO_ICL",
                            Name = "Ingénierie des Composants Logiciels"
                        },
                        new
                        {
                            CourseId = "24027d5d-e151-9a00-fd19-ac11d27b8189",
                            Code = "INFO_TECH",
                            Name = "Technologies Logicielles"
                        },
                        new
                        {
                            CourseId = "3b835d91-4f08-07ef-d4d5-575947097601",
                            Code = "INFO_RO",
                            Name = "Recherche Opérationnelle"
                        },
                        new
                        {
                            CourseId = "02e0e667-183a-1225-d0ed-19fe4c25f963",
                            Code = "GEST_FIN",
                            Name = "Gestion Financière"
                        },
                        new
                        {
                            CourseId = "f4bf5287-38ea-e0ad-d6de-8c9aa20888a0",
                            Code = "DROIT_CONT",
                            Name = "Droit des Contrats"
                        },
                        new
                        {
                            CourseId = "e7d426e1-99eb-6a9f-b9b5-99d9b853e3f5",
                            Code = "GEST_DEV",
                            Name = "Développement Soutenable"
                        },
                        new
                        {
                            CourseId = "03241339-1186-a90f-33bd-a9850f603619",
                            Code = "LANG_ANG",
                            Name = "Anglais"
                        },
                        new
                        {
                            CourseId = "f8c83971-d090-c665-8911-cd645e1a3c87",
                            Code = "PRO_STAGE",
                            Name = "Stage M1"
                        },
                        new
                        {
                            CourseId = "1cb2dee1-fb12-6e48-69ea-2be4c527cbf0",
                            Code = "PRO_MEM",
                            Name = "Rapport d'activité / Mémoire"
                        },
                        new
                        {
                            CourseId = "49ba4385-063d-7b8d-5f3f-aa1c7f573747",
                            Code = "DATA_CRYPTO",
                            Name = "Cryptographie et Sécurité"
                        },
                        new
                        {
                            CourseId = "014c457e-a48a-d25e-7781-d5e483cb3dd9",
                            Code = "DATA_BDD",
                            Name = "Bases de Données Avancées"
                        },
                        new
                        {
                            CourseId = "dd9ec16b-bbf2-e937-3ef4-059bf6b9091d",
                            Code = "DATA_STATS",
                            Name = "Statistiques Appliquées aux Données"
                        },
                        new
                        {
                            CourseId = "731ac32d-6ea9-f15e-7ca2-34f99e840bd3",
                            Code = "DATA_TER",
                            Name = "Travaux d'étude et de recherche (TER)"
                        },
                        new
                        {
                            CourseId = "d059db13-ac91-760c-5bf7-6c442946e7bf",
                            Code = "DATA_ANALYSE",
                            Name = "Analyse de Données"
                        },
                        new
                        {
                            CourseId = "3448ddd0-694c-35d0-f117-7d5834e6ca81",
                            Code = "DATA_INNOV",
                            Name = "Implémentation du Projet Innovation"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("academic_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("track_id");

                    b.HasKey("GroupId")
                        .HasName("PK__Group__D57795A032F181A4");

                    b.HasIndex("TrackId");

                    b.ToTable("Group", (string)null);

                    b.HasData(
                        new
                        {
                            GroupId = "57bf1149-8880-c27c-d603-3546214d03a8",
                            AcademicYear = "2025-2026",
                            Name = "Groupe A - M1 ILSD",
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842FEA1D001E");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Program", b =>
                {
                    b.Property<string>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("program_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("field");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("ProgramId")
                        .HasName("PK__Program__3A7890ACB88F30E8");

                    b.ToTable("Program", (string)null);

                    b.HasData(
                        new
                        {
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            Field = "Informatique & Gestion",
                            Name = "Master MIAGE"
                        },
                        new
                        {
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            Field = "Informatique Fondamentale & Appliquée",
                            Name = "Master Informatique"
                        },
                        new
                        {
                            ProgramId = "6fecdbc8-b9a0-3c82-511f-b30cc40fa9df",
                            Field = "Physique Fondamentale & Appliquée",
                            Name = "Master Physique"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("building_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<bool?>("IsAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_available")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("RoomTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_type_id");

                    b.HasKey("RoomId")
                        .HasName("PK__Room__19675A8A523A40B4");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex(new[] { "RoomNumber" }, "UQ__Room__FE22F61BA8D6C767")
                        .IsUnique();

                    b.ToTable("Room", (string)null);

                    b.HasData(
                        new
                        {
                            RoomId = "02bcf600-5d44-cca7-8b68-e763b00a6339",
                            BuildingId = "2e79e28c-e7d5-27ea-f06e-6c6bb037b3d1",
                            Capacity = 40,
                            IsAvailable = true,
                            RoomNumber = "A-102",
                            RoomTypeId = "2ebbc802-19e3-1c66-7809-e0126364f9f3"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.RoomType", b =>
                {
                    b.Property<string>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_type_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("RoomTypeId")
                        .HasName("PK__RoomType__42395E843B585784");

                    b.HasIndex(new[] { "Name" }, "UQ__RoomType__72E12F1BD83CFC8E")
                        .IsUnique();

                    b.ToTable("RoomType", (string)null);

                    b.HasData(
                        new
                        {
                            RoomTypeId = "2ebbc802-19e3-1c66-7809-e0126364f9f3",
                            Name = "Salle de TD"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room_id");

                    b.Property<string>("SessionStatusId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_status_id");

                    b.Property<string>("SessionTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_type_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("SessionId")
                        .HasName("PK__Session__69B13FDCA8536546");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SessionStatusId");

                    b.HasIndex("SessionTypeId");

                    b.ToTable("Session", (string)null);

                    b.HasData(
                        new
                        {
                            SessionId = "5b7d0dd2-a75d-475e-0f03-d4d2b7f3c55f",
                            CourseId = "2d4557a7-a48d-9926-3e2b-bc820396b11a",
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Mode = "PRESENTIAL",
                            RoomId = "02bcf600-5d44-cca7-8b68-e763b00a6339",
                            SessionStatusId = "09de5696-05df-5b4a-ca95-666d0306b369",
                            SessionTypeId = "7f2d1749-7a62-0b12-0f4e-3b943af03674",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionChange", b =>
                {
                    b.Property<string>("SessionChangeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_change_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("change_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangeStatusId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("change_status_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_id");

                    b.HasKey("SessionChangeId")
                        .HasName("PK__SessionC__D5E31D8F21E5A4A9");

                    b.HasIndex("AdminId");

                    b.HasIndex("ChangeStatusId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SessionChange", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionStatus", b =>
                {
                    b.Property<string>("SessionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_status_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.HasKey("SessionStatusId")
                        .HasName("PK__SessionS__2155C5FD91FDE861");

                    b.HasIndex(new[] { "Label" }, "UQ__SessionS__4823FDB2F2E6150E")
                        .IsUnique();

                    b.ToTable("SessionStatus", (string)null);

                    b.HasData(
                        new
                        {
                            SessionStatusId = "09de5696-05df-5b4a-ca95-666d0306b369",
                            Label = "Programmé"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionType", b =>
                {
                    b.Property<string>("SessionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_type_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.HasKey("SessionTypeId")
                        .HasName("PK__SessionT__FDFD72DC103257F8");

                    b.HasIndex(new[] { "Label" }, "UQ__SessionT__4823FDB29B0B4B02")
                        .IsUnique();

                    b.ToTable("SessionType", (string)null);

                    b.HasData(
                        new
                        {
                            SessionTypeId = "7f2d1749-7a62-0b12-0f4e-3b943af03674",
                            Label = "Cours Magistral"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Student", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_id");

                    b.HasKey("UserId")
                        .HasName("PK__Student__B9BE370F16202FD8");

                    b.HasIndex("GroupId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b49e8575-9a94-b93d-703c-1fc9cf200f96",
                            GroupId = "57bf1149-8880-c27c-d603-3546214d03a8"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Teacher", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration_number");

                    b.Property<string>("TeacherTitleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_title_id");

                    b.HasKey("UserId")
                        .HasName("PK__Teacher__B9BE370F6574A8CD");

                    b.HasIndex("TeacherTitleId");

                    b.HasIndex(new[] { "RegistrationNumber" }, "UQ__Teacher__125DB2A3F2E1D6C6")
                        .IsUnique();

                    b.ToTable("Teacher", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "455c6918-8f55-8171-e3b6-573e17977cfc",
                            RegistrationNumber = "REG_001",
                            TeacherTitleId = "025afe74-4e45-ca60-93e0-035aa84f648d"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.TeacherTitle", b =>
                {
                    b.Property<string>("TeacherTitleId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_title_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("TeacherTitleId")
                        .HasName("PK__TeacherT__E0AD9FB30F212BF5");

                    b.HasIndex(new[] { "Name" }, "UQ__TeacherT__72E12F1B2FE6B18C")
                        .IsUnique();

                    b.ToTable("TeacherTitle", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherTitleId = "025afe74-4e45-ca60-93e0-035aa84f648d",
                            Name = "Professeur"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Track", b =>
                {
                    b.Property<string>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("track_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("program_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_id");

                    b.HasKey("TrackId")
                        .HasName("PK__Track__24ECC82E86A583BD");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Track", (string)null);

                    b.HasData(
                        new
                        {
                            TrackId = "b4f9989d-1aa6-eb1c-b68d-f02b595a4e91",
                            Name = "M1 Informatique Décisionnelle - Apprentissage",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "34d303a1-eecd-13ed-de46-36c8efe0f0d5",
                            Name = "M1 Ingénierie Logicielle pour la Science des Données - Apprentissage",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "7e30cfbb-d683-d9c0-bbd0-e7bf86f6bcd3",
                            Name = "M1 Ingénierie Logicielle pour la Science des Données",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "86de5246-d552-d203-3cfb-450e00d82845",
                            Name = "M2 Informatique Décisionnelle - Apprentissage",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "ce0e0c1e-322e-f894-4476-dc9682a4bdea",
                            Name = "M2 Ingénierie Logicielle pour la Science des Données - Apprentissage",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "16e8879d-d190-3771-1b74-ca91c2f021fe",
                            Name = "M2 Ingénierie Logicielle pour la Science des Données",
                            ProgramId = "1c6c23e0-16b5-6208-2733-cf363a81e9d2",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "5942bd81-7485-6e92-c7e6-66ad363c6bee",
                            Name = "M1 Artificial Intelligence",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "900f1499-bb04-690c-9394-eeafda3848a4",
                            Name = "M1 Computer and Network Systems",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "4defa7f6-3ce5-c643-a522-861cf94ee2e7",
                            Name = "M1 Master parisien de recherche en Informatique (MPRI)",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "4a9d5b23-9f25-3816-a32e-0f206d9b4bb6",
                            Name = "M2 Artificial Intelligence",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "e06ac778-10f0-5ca0-04e6-0df679676eb3",
                            Name = "M2 Computer and Network Systems (CNS) - Systèmes Autonomiques",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        },
                        new
                        {
                            TrackId = "ec7f0b9a-dbe5-a250-41e3-d2857ef80ccf",
                            Name = "M2 Master parisien de recherche en Informatique (MPRI)",
                            ProgramId = "64cb6778-fd4f-ba09-1402-010a1e0e30ce",
                            TeacherId = "455c6918-8f55-8171-e3b6-573e17977cfc"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UnavailableDay", b =>
                {
                    b.Property<string>("UnavailableDayId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unavailable_day_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("UnavailableDayTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unavailable_day_type_id");

                    b.HasKey("UnavailableDayId")
                        .HasName("PK__Unavaila__C40999EABBDBA6A9");

                    b.HasIndex("UnavailableDayTypeId");

                    b.ToTable("UnavailableDay", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UnavailableDayType", b =>
                {
                    b.Property<string>("UnavailableDayTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unavailable_day_type_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("UnavailableDayTypeId")
                        .HasName("PK__Unavaila__A069F8F805C63049");

                    b.HasIndex(new[] { "Name" }, "UQ__Unavaila__72E12F1BF8500212")
                        .IsUnique();

                    b.ToTable("UnavailableDayType", (string)null);
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("UserRoleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_role_id");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370F14AAA68A");

                    b.HasIndex("UserRoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164E818E98E")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c22107c-0651-f328-9d16-c4eb18aed5c3",
                            CreatedAt = new DateTime(2026, 2, 7, 13, 20, 14, 189, DateTimeKind.Utc).AddTicks(2589),
                            Email = "admin@univ.fr",
                            FirstName = "System",
                            LastName = "Admin",
                            Password = "admin123",
                            PhoneNumber = "0000000000",
                            UserRoleId = "0a5d76e1-f1e4-946f-9f3c-d757a576d60e"
                        },
                        new
                        {
                            UserId = "455c6918-8f55-8171-e3b6-573e17977cfc",
                            CreatedAt = new DateTime(2026, 2, 7, 13, 20, 14, 189, DateTimeKind.Utc).AddTicks(2629),
                            Email = "marie.curie@univ.fr",
                            FirstName = "Marie",
                            LastName = "Curie",
                            Password = "pass123",
                            PhoneNumber = "0123456789",
                            UserRoleId = "4c92966c-ae01-8e31-eb08-fa56e3a54d2a"
                        },
                        new
                        {
                            UserId = "b49e8575-9a94-b93d-703c-1fc9cf200f96",
                            CreatedAt = new DateTime(2026, 2, 7, 13, 20, 14, 189, DateTimeKind.Utc).AddTicks(2931),
                            Email = "jean.dupont@etud.fr",
                            FirstName = "Jean",
                            LastName = "Dupont",
                            Password = "pass_jean",
                            PhoneNumber = "0987654321",
                            UserRoleId = "3eca46e4-1e66-8343-3f88-c667fd48550e"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UserRole", b =>
                {
                    b.Property<string>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_role_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("UserRoleId")
                        .HasName("PK__UserRole__B8D9ABA28E202902");

                    b.HasIndex(new[] { "Name" }, "UQ__UserRole__72E12F1B2D3E741A")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserRoleId = "0a5d76e1-f1e4-946f-9f3c-d757a576d60e",
                            Name = "Admin"
                        },
                        new
                        {
                            UserRoleId = "4c92966c-ae01-8e31-eb08-fa56e3a54d2a",
                            Name = "Teacher"
                        },
                        new
                        {
                            UserRoleId = "3eca46e4-1e66-8343-3f88-c667fd48550e",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.WeekDay", b =>
                {
                    b.Property<string>("WeekdayId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("weekday_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<byte>("OrderIndex")
                        .HasColumnType("tinyint")
                        .HasColumnName("order_index");

                    b.HasKey("WeekdayId")
                        .HasName("PK__WeekDay__A22693C27BF1A566");

                    b.HasIndex(new[] { "Name" }, "UQ__WeekDay__72E12F1B20DB09AA")
                        .IsUnique();

                    b.HasIndex(new[] { "OrderIndex" }, "UQ__WeekDay__BB0767F6AAD89115")
                        .IsUnique();

                    b.ToTable("WeekDay", (string)null);

                    b.HasData(
                        new
                        {
                            WeekdayId = "a1572cec-402d-a254-39ac-c88335d6d1d1",
                            Name = "Lundi",
                            OrderIndex = (byte)1
                        });
                });

            modelBuilder.Entity("Receive", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId", "UserId")
                        .HasName("PK__Receive__0BC2675F6B31FA1F");

                    b.HasIndex("UserId");

                    b.ToTable("Receive", (string)null);
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("teacher_id");

                    b.HasKey("SessionId", "TeacherId")
                        .HasName("PK__Teach__998BD8AB8CF334DE");

                    b.HasIndex("TeacherId");

                    b.ToTable("Teach", (string)null);
                });

            modelBuilder.Entity("Attend", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Attend_Group");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Attend_Session");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Admin", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("HP2.Infrastructure.Persistence.Entities.Admin", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Assign", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Course", "Course")
                        .WithMany("Assigns")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Course");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Track", "Track")
                        .WithMany("Assigns")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Track");

                    b.Navigation("Course");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Availability", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Teacher", "Teacher")
                        .WithMany("Availabilities")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Avail_Teacher");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.WeekDay", "Weekday")
                        .WithMany("Availabilities")
                        .HasForeignKey("WeekdayId")
                        .IsRequired()
                        .HasConstraintName("FK_Avail_Weekday");

                    b.Navigation("Teacher");

                    b.Navigation("Weekday");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Group", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Track", "Track")
                        .WithMany("Groups")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK_Group_Track");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Room", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Building");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Type");

                    b.Navigation("Building");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Course");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Room");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.SessionStatus", "SessionStatus")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Status");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.SessionType", "SessionType")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Type");

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("SessionStatus");

                    b.Navigation("SessionType");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionChange", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Admin", "Admin")
                        .WithMany("SessionChanges")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_Change_Admin");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.ChangeStatus", "ChangeStatus")
                        .WithMany("SessionChanges")
                        .HasForeignKey("ChangeStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Change_Status");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Session", "Session")
                        .WithMany("SessionChanges")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Change_Session");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Teacher", "Teacher")
                        .WithMany("SessionChanges")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Change_Teacher");

                    b.Navigation("Admin");

                    b.Navigation("ChangeStatus");

                    b.Navigation("Session");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Student", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Student_Group");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("HP2.Infrastructure.Persistence.Entities.Student", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Student_User");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Teacher", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.TeacherTitle", "TeacherTitle")
                        .WithMany("Teachers")
                        .HasForeignKey("TeacherTitleId")
                        .IsRequired()
                        .HasConstraintName("FK_Teacher_Title");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("HP2.Infrastructure.Persistence.Entities.Teacher", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Teacher_User");

                    b.Navigation("TeacherTitle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Track", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Program", "Program")
                        .WithMany("Tracks")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("FK_Track_Program");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Teacher", "Teacher")
                        .WithMany("Tracks")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Track_Teacher");

                    b.Navigation("Program");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UnavailableDay", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.UnavailableDayType", "UnavailableDayType")
                        .WithMany("UnavailableDays")
                        .HasForeignKey("UnavailableDayTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Unavail_Type");

                    b.Navigation("UnavailableDayType");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Receive", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_Receive_Notif");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Receive_User");
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Teach_Session");

                    b.HasOne("HP2.Infrastructure.Persistence.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Teach_Teacher");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Admin", b =>
                {
                    b.Navigation("SessionChanges");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.ChangeStatus", b =>
                {
                    b.Navigation("SessionChanges");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Course", b =>
                {
                    b.Navigation("Assigns");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Program", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.Navigation("SessionChanges");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionStatus", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.SessionType", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Teacher", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("SessionChanges");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.TeacherTitle", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.Track", b =>
                {
                    b.Navigation("Assigns");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UnavailableDayType", b =>
                {
                    b.Navigation("UnavailableDays");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HP2.Infrastructure.Persistence.Entities.WeekDay", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
