name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /home/mohamed/backend
            cd /home/mohamed/backend
            git fetch origin
            git checkout main
            git reset --hard origin/main
            echo "Deploying commit: $(git rev-parse --short HEAD)"
            cd /home/mohamed/backend/api
            docker-compose down -v
            docker-compose up --build -d
